# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_word',
            field=models.CharField(default='workshop', max_length=30),
        ),
    ]
